name: IUM s424714

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      epochs:
        description: 'Epochs'
        required: true
        default: "1"
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: |
          echo ${{ github.event.inputs.epochs }}
          echo "${{ github.event.inputs.epochs }}"
          docker build -t mamba .
        working-directory: ./

      - name: Run Docker image (train process)
        run: |
          docker run mamba python src/main.py  -e="${{ github.event.inputs.epochs }}"

      - name: Copy model.pt
        run: |
          docker cp $(docker ps -lq):results/model.pt .
      
  test:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2