name: IUM s424714

on:
    push:
        branches:
            - master
    workflow_dispatch:
        inputs:
            training_params:
            description: 'Epochs'
            required: true
            default: '1'

    jobs:
        checkout_repo:
            runs-on: ubuntu-latest
            steps:
                - name: Checkout repo
                  uses: actions/check